apiVersion: v1
kind: Pod
metadata:
 name: probe
spec:
 containers:
   - name: app
     image: python:3.11-alpine
     command: ["/bin/sh", "-c"]
     args:
       - touch /tmp/ready /tmp/healthy && python -m http.server 8080
     ports:
       - containerPort: 8080
     readinessProbe:
       exec:
         command: ["cat", "/tmp/ready"]
       initialDelaySeconds: 3
       periodSeconds: 3
     livenessProbe:
       exec:
         command: ["cat", "/tmp/healthy"]
       initialDelaySeconds: 5
       periodSeconds: 5