apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: my-config
        configMap: 
          name: nginx-cm
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
          - name: app
            valueFrom: 
              configMapKeyRef: 
                name: nginx-cm
                key: app
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/etc/nginx/conf.d"
          name: my-config