apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 name: databases.myorg.com
spec:
 group: myorg.com
 names:
   kind: Database
   plural: databases
   singular: database
   shortNames:
     - db
 scope: Namespaced
 versions:
   - name: v1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           spec:
             type: object
             properties:
               engine:
                 type: string
                 enum:
                   - mysql
                   - postgresql
               version:
                 type: string
               storageSize:
                 type: string
                 example: "10Gi"
               replicas:
                 type: integer
             required:
               - engine
               - version
               - storageSize








